[package]
name = "basic_bitcoin_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = { version = "0.30.0", features = ["global-context", "rand", "std"] }
serde_json = "1.0.133"
sha2 = "0.10.8"
thiserror = "2.0.6"
